name: CI
on:
  pull_request:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        channel: beta
    - run: flutter config --enable-web
    - run: flutter pub get
    - run: flutter build web
    - name: Release Web
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/web"
